# Generated by Django 5.2.16 on 2026-07-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MandatoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='Channel ID (e.g., -100xxxx) or username (e.g., @channel_name)', max_length=255)),
                ('channel_link', models.URLField(help_text='Public invite link (e.g., https://t.me/channel_name)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mandatory Channel',
                'verbose_name_plural': 'Mandatory Channels',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField()),
                ('hashtags_found', models.TextField(blank=True, default='', help_text='Comma-separated list of hashtags found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='botapp.botuser')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
