# Generated by Django 5.2.16 on 2026-07-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Foydalanuvchini taklif qilgan boshqa foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='botapp.botuser'),
        ),
    ]
