# Generated by Django 5.2.16 on 2026-07-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_botuser_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='VipChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='VIP Channel Telegram ID', max_length=255)),
                ('invite_link', models.URLField(help_text='VIP Channel taklif havolasi')),
                ('is_active', models.BooleanField(default=True, help_text='Ushbu taklif havolasi faolmi?')),
            ],
            options={
                'verbose_name': 'VIP Channel',
                'verbose_name_plural': 'VIP Channels',
            },
        ),
        migrations.AddField(
            model_name='botuser',
            name='has_vip_access',
            field=models.BooleanField(default=False, help_text="VIP kanalga kirish ruxsati bor yoki yo'qligi"),
        ),
        migrations.AddField(
            model_name='botuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Foydalanuvchining shaxsiy taklif kodi', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='total_coins',
            field=models.PositiveIntegerField(default=0, help_text='Foydalanuvchining umumiy tangalari balansi'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='vip_unlocked_at',
            field=models.DateTimeField(blank=True, help_text='VIP kanal ruxsati ochilgan sana va vaqt', null=True),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text="Qo'shilgan (+) yoki ayirilgan (-) tanga miqdori")),
                ('reason', models.CharField(help_text='Tanga tranzaksiyasi sababi', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Tanga olgan yoki sarflagan foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='botapp.botuser')),
            ],
            options={
                'verbose_name': 'Coin Transaction',
                'verbose_name_plural': 'Coin Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
