# Generated by Django 5.2.16 on 2026-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_systemsetting_vipchannel_botuser_has_vip_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0, help_text="Jami taklif qilingan do'stlar soni"),
        ),
    ]
